// Спец-ноды K2 (R40) — шаблонный путь: блоки сняты с живого copy-back UE 5.8
// (sweep/copyback/r40-special-nodes.txt), перегенерируются со свежими GUID/именами,
// без LinkedTo, с открытым пузырём комментария. Генератор НЕ двигает и НЕ соединяет ноды:
// pos — только стартовая точка (0,0 по умолчанию), координаты ставит расстановщик.
import fs from 'fs';
import { fileURLToPath } from 'url';
import { parseToGraphs, guid32 } from './parser.js';

const SRC = fileURLToPath(new URL('../sweep/copyback/r40-special-nodes.txt', import.meta.url));
let TPL = null;
function templates() {
  if (TPL) return TPL;
  TPL = {};
  for (const n of parseToGraphs(fs.readFileSync(SRC, 'utf8')).EventGraph.nodes) TPL[n.rawName] = n.rawBlock;
  return TPL;
}

const PIN_TAIL = 'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,';
const PIN_END = 'bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)';

const counters = {};
function nextName(cls) { counters[cls] = (counters[cls] ?? 1000) + 1; return `${cls}_${counters[cls]}`; }
export function resetSpecialCounters() { for (const k in counters) delete counters[k]; }

// Свежие GUID для NodeGuid/PinId (внутренние ссылки ReferencePassThroughConnection переписываются согласованно),
// PersistentGuid полей структур НЕ трогаем — это GUID полей ассета.
function refresh(block, { name, pos, bubble, drop = [] }) {
  const oldName = block.match(/Name="([^"]+)"/)[1];
  const map = {};
  block = block.replace(/PinId=([0-9A-F]{32})/g, (_, g) => `PinId=${(map[g] = guid32())}`);
  block = block.replace(new RegExp(`${oldName} ([0-9A-F]{32})`, 'g'), (_, g) => `${name} ${map[g] ?? g}`);
  block = block.replace(/ ExportPath="[^"]*"/, '').replace(`Name="${oldName}"`, `Name="${name}"`);
  block = block.replace(/LinkedTo=\([^)]*\),/g, '');
  block = block.replace(/\n\s*(bHasCompilerMessage|ErrorType|ErrorMsg)=[^\n]*/g, '');
  for (const re of drop) block = block.replace(re, '');
  block = block.replace(/NodePosX=-?\d+/, `NodePosX=${pos.x}`).replace(/NodePosY=-?\d+/, `NodePosY=${pos.y}`);
  const b = bubble ? `   bCommentBubbleVisible=True\n   NodeComment="${String(bubble).replace(/"/g, "'")}"\n` : '';
  return block.replace(/(\n\s*)NodeGuid=[0-9A-F]{32}/, `\n${b}   NodeGuid=${guid32()}`);
}

function toNode(text) { return parseToGraphs(text).EventGraph.nodes[0]; }
const P = (o) => ({ pos: o.pos ?? { x: 0, y: 0 }, bubble: o.bubble });

// ── Timeline. Шаблон таймлайна (кривые) живёт в самом BP: нода без ассета TimelineTemplate
//    вставится, но скомпилируется с ошибкой — это ограничение движка, не формата.
export function createTimeline(o = {}) {
  const name = nextName('K2Node_Timeline');
  let b = refresh(templates().K2Node_Timeline_0, { name, ...P(o) });
  b = b.replace(/TimelineName="[^"]*"/, `TimelineName="${o.timelineName ?? 'Timeline'}"`)
       .replace(/TimelineGuid=[0-9A-F]{32}/, `TimelineGuid=${guid32()}`);
  return toNode(b);
}

// ── Interface Message (K2Node_Message). Требует BPI-класс с функцией memberName (+memberGuid из BPI).
//    params: [{name, category:'real', sub:'double', def:'0.0'}] — входные параметры функции интерфейса.
export function createInterfaceMessage(o) {
  const name = nextName('K2Node_Message');
  let b = refresh(templates().K2Node_Message_0, { name, ...P(o) });
  b = b.replace(/FunctionReference=\([^\n]*\)/,
    `FunctionReference=(MemberParent="/Script/Engine.BlueprintGeneratedClass'${o.bpiPath}'",MemberName="${o.memberName}",MemberGuid=${o.memberGuid ?? guid32()})`);
  const extra = (o.params ?? []).map(p => {
    const d = p.def != null ? `DefaultValue="${p.def}",AutogeneratedDefaultValue="${p.def}",` : '';
    return `   CustomProperties Pin (PinId=${guid32()},PinName="${p.name}",PinType.PinCategory="${p.category}",PinType.PinSubCategory="${p.sub ?? ''}",PinType.PinSubCategoryObject=${p.subObject ? `"${p.subObject}"` : 'None'},${PIN_TAIL}${d}PersistentGuid=00000000000000000000000000000000,${PIN_END}`;
  }).join('\n');
  if (extra) b = b.replace(/\nEnd Object$/, `\n${extra}\nEnd Object`);
  return toNode(b);
}

// ── AI MoveTo (AIGraph.K2Node_AIMoveTo) — пины фиксированы движком.
export function createAIMoveTo(o = {}) {
  return toNode(refresh(templates().K2Node_AIMoveTo_0, { name: nextName('K2Node_AIMoveTo'), ...P(o) }));
}

// ── GetDataTableRow. Без dataTable — wildcard-выход (нода ругается «No DataTable», как в движке).
//    С dataTable:{path, rowStruct} — DefaultObject на пине DataTable и struct-выход.
export function createGetDataTableRow(o = {}) {
  let b = refresh(templates().K2Node_GetDataTableRow_1, { name: nextName('K2Node_GetDataTableRow'), ...P(o) });
  if (o.dataTable) {
    b = b.replace(/(PinName="DataTable",[^\n]*?)PersistentGuid=/, `$1DefaultObject="${o.dataTable.path}",PersistentGuid=`)
         .replace(/(PinName="ReturnValue",[^\n]*?)PinType.PinCategory="wildcard",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None/,
           `$1PinType.PinCategory="struct",PinType.PinSubCategory="",PinType.PinSubCategoryObject="${o.dataTable.rowStruct}"`);
    if (o.rowName) b = b.replace(/(PinName="RowName",[^\n]*?)PersistentGuid=/, `$1DefaultValue="${o.rowName}",PersistentGuid=`);
  }
  return toNode(b);
}

// ── UserDefinedStruct Make/Break/SetFields.
//    struct: {path:'/Game/S_MinMax.S_MinMax', name:'S_MinMax', fields:[{prop:'Min_2_<GUID>', friendly:'Min', category:'real', sub:'double', def:'0.000000'}]}
function structObj(s) { return `/Script/CoreUObject.UserDefinedStruct'${s.path}'`; }
function fieldPin(f, dir) {
  const guid = f.prop.match(/_([0-9A-F]{32})$/)?.[1] ?? '00000000000000000000000000000000';
  const d = dir === 'in' && f.def != null ? `DefaultValue="${f.def}",AutogeneratedDefaultValue="${f.def}",` : '';
  const dr = dir === 'out' ? 'Direction="EGPD_Output",' : '';
  return `   CustomProperties Pin (PinId=${guid32()},PinName="${f.prop}",PinFriendlyName=INVTEXT("${f.friendly}"),${dr}PinType.PinCategory="${f.category}",PinType.PinSubCategory="${f.sub ?? ''}",PinType.PinSubCategoryObject=${f.subObject ? `"${f.subObject}"` : 'None'},${PIN_TAIL}${d}PersistentGuid=${guid},${PIN_END}`;
}
function structNode(tplName, cls, o, { show, fieldDir }) {
  const s = o.struct;
  let b = refresh(templates()[tplName], { name: nextName(cls), ...P(o) });
  b = b.replace(/\n\s*ShowPinForProperties\(\d+\)=[^\n]*/g, '')
       .replace(/StructType="[^"]*"/, `StructType="${structObj(s)}"`)
       .replace(/\/Script\/CoreUObject\.UserDefinedStruct'[^']*'/g, structObj(s))
       .replace(/PinName="S_MinMax"/g, `PinName="${s.name}"`);
  const spf = s.fields.map((f, i) => `   ShowPinForProperties(${i})=(PropertyName="${f.prop}",PropertyFriendlyName="${f.friendly}",${show ? 'bShowPin=True,' : ''}bCanToggleVisibility=True)`).join('\n');
  b = b.replace(/(\n\s*StructType=)/, `\n${spf}$1`);
  b = b.replace(/\n\s*CustomProperties Pin \(PinId=[0-9A-F]{32},PinName="[A-Za-z0-9]+_\d+_[0-9A-F]{32}"[^\n]*/g, '');
  if (fieldDir) b = b.replace(/\nEnd Object$/, `\n${s.fields.map(f => fieldPin(f, fieldDir)).join('\n')}\nEnd Object`);
  return toNode(b);
}
export const createMakeUserStruct = (o) => structNode('K2Node_MakeStruct_1', 'K2Node_MakeStruct', o, { show: true, fieldDir: 'in' });
export const createBreakUserStruct = (o) => structNode('K2Node_BreakStruct_2', 'K2Node_BreakStruct', o, { show: true, fieldDir: 'out' });
// SetFields: поля по умолчанию скрыты (как в движке — без bShowPin), пины полей не пишутся.
export const createSetFieldsInUserStruct = (o) => structNode('K2Node_SetFieldsInStruct_1', 'K2Node_SetFieldsInStruct', o, { show: false, fieldDir: null });

// ── Set by-ref (K2Node_VariableSetRef) — wildcard Target(ref)/Value.
export function createVariableSetRef(o = {}) {
  return toNode(refresh(templates().K2Node_VariableSetRef_0, { name: nextName('K2Node_VariableSetRef'), ...P(o) }));
}

export const SPECIAL_KINDS = ['Timeline', 'InterfaceMessage', 'AIMoveTo', 'GetDataTableRow', 'MakeUserStruct', 'BreakUserStruct', 'SetFieldsInUserStruct', 'VariableSetRef'];
