// Спец-ноды K2 (R40) — шаблонный путь: блоки сняты с живого copy-back UE 5.8
// (sweep/copyback/r40-special-nodes.txt), перегенерируются со свежими GUID/именами,
// без LinkedTo, с открытым пузырём комментария. Генератор НЕ двигает и НЕ соединяет ноды:
// pos — только стартовая точка (0,0 по умолчанию), координаты ставит расстановщик.
import fs from 'fs';
import { fileURLToPath } from 'url';
import { parseToGraphs, guid32 } from './parser.js';

const SRC = fileURLToPath(new URL('../sweep/copyback/r40-special-nodes.txt', import.meta.url));
const EASE_SRC = fileURLToPath(new URL('../sweep/copyback/ease-r43.txt', import.meta.url)); // R43 copy-back
let TPL = null;
function templates() {
  if (TPL) return TPL;
  TPL = {};
  for (const f of [SRC, EASE_SRC])
    for (const n of parseToGraphs(fs.readFileSync(f, 'utf8')).EventGraph.nodes) TPL[n.rawName] = n.rawBlock;
  return TPL;
}

// R49 copy-back (спец-ноды: enum/class/async/asset/RPC/parent/bind) — отдельная карта, имена блоков пересекаются с r40.
const R49_SRC = fileURLToPath(new URL('../sweep/copyback/r49-special-nodes.txt', import.meta.url));
const R51_SRC = fileURLToPath(new URL('../sweep/copyback/r51-dragdrop.txt', import.meta.url));
let TPL49 = null;
function tpl49(k) {
  if (!TPL49) { TPL49 = {}; for (const f of [R49_SRC, R51_SRC]) for (const n of parseToGraphs(fs.readFileSync(f, 'utf8')).EventGraph.nodes) TPL49[n.rawName] = n.rawBlock; }
  if (!TPL49[k]) throw new Error(`r49: нет шаблона ${k}`);
  return TPL49[k];
}

const PIN_TAIL = 'PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,';
const PIN_END = 'bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)';

const counters = {};
function nextName(cls) { counters[cls] = (counters[cls] ?? 1000) + 1; return `${cls}_${counters[cls]}`; }
export function resetSpecialCounters() { for (const k in counters) delete counters[k]; }

// Свежие GUID для NodeGuid/PinId (внутренние ссылки ReferencePassThroughConnection переписываются согласованно),
// PersistentGuid полей структур НЕ трогаем — это GUID полей ассета.
function refresh(block, { name, pos, bubble, drop = [] }) {
  const oldName = block.match(/Name="([^"]+)"/)[1];
  const map = {};
  block = block.replace(/PinId=([0-9A-F]{32})/g, (_, g) => `PinId=${(map[g] = guid32())}`);
  block = block.replace(new RegExp(`${oldName} ([0-9A-F]{32})`, 'g'), (_, g) => `${name} ${map[g] ?? g}`);
  block = block.replace(/ ExportPath="[^"]*"/, '').replace(`Name="${oldName}"`, `Name="${name}"`);
  block = block.replace(/LinkedTo=\([^)]*\),/g, '');
  block = block.replace(/\n\s*(bHasCompilerMessage|ErrorType|ErrorMsg)=[^\n]*/g, '');
  for (const re of drop) block = block.replace(re, '');
  block = block.replace(/NodePosX=-?\d+/, `NodePosX=${pos.x}`).replace(/NodePosY=-?\d+/, `NodePosY=${pos.y}`);
  const b = bubble ? `   bCommentBubbleVisible=True\n   NodeComment="${String(bubble).replace(/"/g, "'")}"\n` : '';
  return block.replace(/(\n\s*)NodeGuid=[0-9A-F]{32}/, `\n${b}   NodeGuid=${guid32()}`);
}

function toNode(text) { return parseToGraphs(text).EventGraph.nodes[0]; }
const P = (o) => ({ pos: o.pos ?? { x: 0, y: 0 }, bubble: o.bubble });

// ── Timeline. Шаблон таймлайна (кривые) живёт в самом BP: нода без ассета TimelineTemplate
//    вставится, но скомпилируется с ошибкой — это ограничение движка, не формата.
export function createTimeline(o = {}) {
  const name = nextName('K2Node_Timeline');
  let b = refresh(templates().K2Node_Timeline_0, { name, ...P(o) });
  b = b.replace(/TimelineName="[^"]*"/, `TimelineName="${o.timelineName ?? 'Timeline'}"`)
       .replace(/TimelineGuid=[0-9A-F]{32}/, `TimelineGuid=${guid32()}`);
  return toNode(b);
}

// ── Interface Message (K2Node_Message). Требует BPI-класс с функцией memberName (+memberGuid из BPI).
//    params: [{name, category:'real', sub:'double', def:'0.0'}] — входные параметры функции интерфейса.
export function createInterfaceMessage(o) {
  const name = nextName('K2Node_Message');
  let b = refresh(templates().K2Node_Message_0, { name, ...P(o) });
  b = b.replace(/FunctionReference=\([^\n]*\)/,
    `FunctionReference=(MemberParent="/Script/Engine.BlueprintGeneratedClass'${o.bpiPath}'",MemberName="${o.memberName}",MemberGuid=${o.memberGuid ?? guid32()})`);
  const extra = (o.params ?? []).map(p => {
    const d = p.def != null ? `DefaultValue="${p.def}",AutogeneratedDefaultValue="${p.def}",` : '';
    return `   CustomProperties Pin (PinId=${guid32()},PinName="${p.name}",PinType.PinCategory="${p.category}",PinType.PinSubCategory="${p.sub ?? ''}",PinType.PinSubCategoryObject=${p.subObject ? `"${p.subObject}"` : 'None'},${PIN_TAIL}${d}PersistentGuid=00000000000000000000000000000000,${PIN_END}`;
  }).join('\n');
  if (extra) b = b.replace(/\nEnd Object$/, `\n${extra}\nEnd Object`);
  return toNode(b);
}

// ── Ease (K2Node_EaseFunction, R43 copy-back) — НЕ вызов KismetMathLibrary.Ease, а своя K2-нода:
//    A/B/Result — wildcard (тип по подключению), Function — EEasingFunc; BlendExp/Steps/ShortestPath
//    скрыты движком, пока Function их не требует. easing — имя значения EEasingFunc (Linear, EaseIn, …).
export function createEaseFunction(o = {}) {
  let b = refresh(templates().K2Node_EaseFunction_0, { name: nextName('K2Node_EaseFunction'), ...P(o) });
  if (o.easing) b = b.replace(/(PinName="Function",[^\n]*?)DefaultValue="Linear"/, `$1DefaultValue="${o.easing}"`);
  return toNode(b);
}

// ── AI MoveTo (AIGraph.K2Node_AIMoveTo) — пины фиксированы движком.
export function createAIMoveTo(o = {}) {
  return toNode(refresh(templates().K2Node_AIMoveTo_0, { name: nextName('K2Node_AIMoveTo'), ...P(o) }));
}

// ── GetDataTableRow. Без dataTable — wildcard-выход (нода ругается «No DataTable», как в движке).
//    С dataTable:{path, rowStruct} — DefaultObject на пине DataTable и struct-выход.
export function createGetDataTableRow(o = {}) {
  let b = refresh(templates().K2Node_GetDataTableRow_1, { name: nextName('K2Node_GetDataTableRow'), ...P(o) });
  if (o.dataTable) {
    b = b.replace(/(PinName="DataTable",[^\n]*?)PersistentGuid=/, `$1DefaultObject="${o.dataTable.path}",PersistentGuid=`)
         .replace(/(PinName="ReturnValue",[^\n]*?)PinType.PinCategory="wildcard",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None/,
           `$1PinType.PinCategory="struct",PinType.PinSubCategory="",PinType.PinSubCategoryObject="${o.dataTable.rowStruct}"`);
    if (o.rowName) b = b.replace(/(PinName="RowName",[^\n]*?)PersistentGuid=/, `$1DefaultValue="${o.rowName}",PersistentGuid=`);
  }
  return toNode(b);
}

// ── UserDefinedStruct Make/Break/SetFields.
//    struct: {path:'/Game/S_MinMax.S_MinMax', name:'S_MinMax', fields:[{prop:'Min_2_<GUID>', friendly:'Min', category:'real', sub:'double', def:'0.000000'}]}
function structObj(s) { return `/Script/CoreUObject.UserDefinedStruct'${s.path}'`; }
function fieldPin(f, dir) {
  const guid = f.prop.match(/_([0-9A-F]{32})$/)?.[1] ?? '00000000000000000000000000000000';
  const d = dir === 'in' && f.def != null ? `DefaultValue="${f.def}",AutogeneratedDefaultValue="${f.def}",` : '';
  const dr = dir === 'out' ? 'Direction="EGPD_Output",' : '';
  return `   CustomProperties Pin (PinId=${guid32()},PinName="${f.prop}",PinFriendlyName=INVTEXT("${f.friendly}"),${dr}PinType.PinCategory="${f.category}",PinType.PinSubCategory="${f.sub ?? ''}",PinType.PinSubCategoryObject=${f.subObject ? `"${f.subObject}"` : 'None'},${PIN_TAIL}${d}PersistentGuid=${guid},${PIN_END}`;
}
function structNode(tplName, cls, o, { show, fieldDir }) {
  const s = o.struct;
  let b = refresh(templates()[tplName], { name: nextName(cls), ...P(o) });
  b = b.replace(/\n\s*ShowPinForProperties\(\d+\)=[^\n]*/g, '')
       .replace(/StructType="[^"]*"/, `StructType="${structObj(s)}"`)
       .replace(/\/Script\/CoreUObject\.UserDefinedStruct'[^']*'/g, structObj(s))
       .replace(/PinName="S_MinMax"/g, `PinName="${s.name}"`);
  const spf = s.fields.map((f, i) => `   ShowPinForProperties(${i})=(PropertyName="${f.prop}",PropertyFriendlyName="${f.friendly}",${show ? 'bShowPin=True,' : ''}bCanToggleVisibility=True)`).join('\n');
  b = b.replace(/(\n\s*StructType=)/, `\n${spf}$1`);
  b = b.replace(/\n\s*CustomProperties Pin \(PinId=[0-9A-F]{32},PinName="[A-Za-z0-9]+_\d+_[0-9A-F]{32}"[^\n]*/g, '');
  if (fieldDir) b = b.replace(/\nEnd Object$/, `\n${s.fields.map(f => fieldPin(f, fieldDir)).join('\n')}\nEnd Object`);
  return toNode(b);
}
export const createMakeUserStruct = (o) => structNode('K2Node_MakeStruct_1', 'K2Node_MakeStruct', o, { show: true, fieldDir: 'in' });
export const createBreakUserStruct = (o) => structNode('K2Node_BreakStruct_2', 'K2Node_BreakStruct', o, { show: true, fieldDir: 'out' });
// SetFields: поля по умолчанию скрыты (как в движке — без bShowPin), пины полей не пишутся.
export const createSetFieldsInUserStruct = (o) => structNode('K2Node_SetFieldsInStruct_1', 'K2Node_SetFieldsInStruct', o, { show: false, fieldDir: null });

// ── Set by-ref (K2Node_VariableSetRef) — wildcard Target(ref)/Value.
export function createVariableSetRef(o = {}) {
  return toNode(refresh(templates().K2Node_VariableSetRef_0, { name: nextName('K2Node_VariableSetRef'), ...P(o) }));
}

// ── R49 ──────────────────────────────────────────────────────────────────────
// Enum to Name/String: вход ОБЯЗАН быть подключён (иначе движок: «Must have non-default Enum input», R49).
// enum: '/Script/Engine.ECollisionChannel' (нативный) | '/Game/.../E_Foo.E_Foo' (UserDefinedEnum) | готовая ссылка с кавычками.
export function enumObj(e) {
  if (e.includes("'")) return e;
  return e.startsWith('/Script/') ? `/Script/CoreUObject.Enum'${e}'` : `/Script/Engine.UserDefinedEnum'${e}'`;
}
const TPL_ENUM_RE = /\/Script\/(?:Engine\.UserDefinedEnum|CoreUObject\.Enum)'[^']*'/g;
function r49(tpl, cls, o, edit = (b) => b) {
  return toNode(edit(refresh(tpl49(tpl), { name: nextName(cls), ...P(o) })));
}
function withEnum(o, value) {
  return (b) => {
    if (!o.enum) throw new Error('enum обязателен');
    b = b.replace(TPL_ENUM_RE, enumObj(o.enum));
    return value === undefined ? b.replace(/DefaultValue="NewEnumerator0",/g, '')
      : b.replace(/DefaultValue="NewEnumerator0"/g, `DefaultValue="${value}"`);
  };
}
export const createEnumLiteral = (o) => r49('K2Node_EnumLiteral_0', 'K2Node_EnumLiteral', o, withEnum(o, o.value ?? 'NewEnumerator0'));
export const createGetEnumeratorName = (o) => r49('K2Node_GetEnumeratorName_1', 'K2Node_GetEnumeratorName', o, withEnum(o));
export const createGetEnumeratorNameAsString = (o) => r49('K2Node_GetEnumeratorNameAsString_1', 'K2Node_GetEnumeratorNameAsString', o, withEnum(o));
export const createCastByteToEnum = (o) => r49('K2Node_CastByteToEnum_3', 'K2Node_CastByteToEnum', o, withEnum(o));
export const createEnumEquality = (o) => r49('K2Node_EnumEquality_0', 'K2Node_EnumEquality', o, withEnum(o, o.b));
export const createForEachEnum = (o) => r49('K2Node_ForEachElementInEnum_0', 'K2Node_ForEachElementInEnum', o, withEnum(o));

// class: '/Script/Engine.Character' | '/Game/BP/BP_X.BP_X_C'
const classObj = (c) => `/Script/CoreUObject.Class'${c}'`;
export const createSpawnActorFromClass = (o = {}) => r49('K2Node_SpawnActorFromClass_1', 'K2Node_SpawnActorFromClass', o,
  (b) => o.actorClass ? b.replace('DefaultObject="/Script/Engine.Actor"', `DefaultObject="${o.actorClass}"`) : b);
// GetClassDefaults: ShowPinForProperties зависят от класса — не пишем; выходы включаются в Details.
export const createGetClassDefaults = (o = {}) => r49('K2Node_GetClassDefaults_0', 'K2Node_GetClassDefaults', o,
  (b) => b.replace(/\n\s*ShowPinForProperties\(\d+\)=[^\n]*/g, '')
    .replace(/DefaultObject="[^"]*"/, o.class ? `DefaultObject="${o.class}"` : '').replace(/,,/g, ','));
export const createGetSubsystem = (o) => r49('K2Node_GetSubsystem_2', 'K2Node_GetSubsystem', o,
  (b) => b.replace(/\/Script\/CoreUObject\.Class'\/Script\/Engine\.ReplaySubsystem'/g, classObj(o.subsystem)));
export const createLoadAsset = (o = {}) => r49('K2Node_LoadAsset_0', 'K2Node_LoadAsset', o);
export const createLoadAssets = (o = {}) => r49('K2Node_LoadAssets_0', 'K2Node_LoadAssets', o);
export const createLoadAssetClass = (o = {}) => r49('K2Node_LoadAssetClass_0', 'K2Node_LoadAssetClass', o);
export const createAsyncLoadPrimaryAsset = (o = {}) => r49('K2Node_AsyncAction_0', 'K2Node_AsyncAction', o);
// Object → SoftObject; тип пинов уточняется движком по подключению.
export const createConvertAsset = (o = {}) => r49('K2Node_ConvertAsset_1', 'K2Node_ConvertAsset', o,
  (b) => b.replace(/\/Script\/VariantManagerContent\.PropertyValueSoftObject/g, o.class ?? '/Script/CoreUObject.Object'));
export const createPlayMontage = (o = {}) => r49('K2Node_PlayMontage_0', 'K2Node_PlayMontage', o);
export const createSelf = (o = {}) => r49('K2Node_Self_0', 'K2Node_Self', o);
export const createMultiGate = (o = {}) => r49('K2Node_MultiGate_0', 'K2Node_MultiGate', o);
// Parent: BeginPlay → {event:'ReceiveBeginPlay', parent:'/Script/Engine.Actor'}
export const createCallParentFunction = (o = {}) => r49('K2Node_CallParentFunction_0', 'K2Node_CallParentFunction', o,
  (b) => b.replace(/\/Script\/Engine\.Actor/g, o.parent ?? '/Script/Engine.Actor').replace('MemberName="ReceiveBeginPlay"', `MemberName="${o.event ?? 'ReceiveBeginPlay'}"`));
// Bind Event to <delegate>: Event-пин подключается к CustomEvent с сигнатурой делегата.
export const createAssignDelegate = (o = {}) => r49('K2Node_AssignDelegate_0', 'K2Node_AssignDelegate', o, (b) => {
  if (!o.delegate) return b;
  const { owner, name, signature, pkg = '/Script/Engine' } = o.delegate;
  return b.replace(/\/Script\/Engine\.PrimitiveComponent/g, owner).replace('MemberName="OnComponentBeginOverlap"', `MemberName="${name}"`)
    .replace("'/Script/Engine'", `'${pkg}'`).replace('ComponentBeginOverlapSignature__DelegateSignature', signature);
});

// R51: Create Drag Drop Operation (UMGEditor). class — свой DragDropOperation-класс (по умолчанию базовый).
export const createDragDropOperation = (o = {}) => r49('K2Node_CreateDragDropOperation_0', 'K2Node_CreateDragDropOperation', o,
  (b) => o.class ? b.replace('DefaultObject="/Script/UMG.DragDropOperation"', `DefaultObject="${o.class}"`) : b);

export const SPECIAL_KINDS = ['DragDropOperation', 'Timeline', 'InterfaceMessage', 'AIMoveTo', 'GetDataTableRow', 'MakeUserStruct', 'BreakUserStruct', 'SetFieldsInUserStruct', 'VariableSetRef',
  'EnumLiteral', 'GetEnumeratorName', 'GetEnumeratorNameAsString', 'CastByteToEnum', 'EnumEquality', 'ForEachEnum', 'SpawnActorFromClass', 'GetClassDefaults',
  'GetSubsystem', 'LoadAsset', 'LoadAssets', 'LoadAssetClass', 'AsyncLoadPrimaryAsset', 'ConvertAsset', 'PlayMontage', 'Self', 'MultiGate', 'CallParentFunction', 'AssignDelegate'];
