// src/ue-types.js — единый источник правды для путей движка UE.
// Используют: src/generator.js, src/parser.js, src/validate.js, docs, prompt.
// ВАЖНО: дублируется мини-копией в index.html
// (UE_VERSION/UE_LIBS/UE_STRUCTS/UE_ENUMS/classRef/macroRefs) — при изменении синхронизируй оба места.
//
// v6: движок-цель — UE 5.8.0-55116800 (точная строка версии от пользователя, 2026-09-25).
// ВНИМАНИЕ: в v5 движок был ошибочно помечен как UE4 (по пакету CoreUObject) —
// на самом деле это UE 5.8, и именно он пишет ссылки quoted-full:
//   MemberParent="/Script/CoreUObject.Class'/Script/Engine.KismetSystemLibrary'"
//   PinSubCategoryObject="/Script/CoreUObject.ScriptStruct'/Script/CoreUObject.Vector'"
//   PinSubCategoryObject="/Script/CoreUObject.Class'/Script/CoreUObject.Object'"  (WCO-пин)
//   StructType="/Script/CoreUObject.ScriptStruct'/Script/CoreUObject.Vector'"
// Короткая форма (Class'"..."') — legacy (UE4-эпоха и ранние UE5-дампы), вставкой НЕ проверена.
// Struct-пины: PinSubCategory="" (ПУСТО! имя типа только из SubCategoryObject).
// Struct-входы функций — bIsConst=True (Start/End трейса), дефолт Vector "0, 0, 0".
// Enum-пины: byte + quoted-full Enum-путь + DefaultValue=имя элемента (без Autogenerated).
// Массив объектов: ContainerType=Array + bIsReference=True + bIsConst=True + bDefaultValueIsIgnored=True.

// Формат ссылок: 'FULL' (quoted-full, проверено UE 5.8.0) | 'SHORT' (legacy, вставкой не проверено).
export const UE_VERSION = 'FULL';

const LIBS_FULL = {
  KismetMathLibrary:   `"/Script/CoreUObject.Class'/Script/Engine.KismetMathLibrary'"`,
  KismetSystemLibrary: `"/Script/CoreUObject.Class'/Script/Engine.KismetSystemLibrary'"`,
  KismetStringLibrary: `"/Script/CoreUObject.Class'/Script/Engine.KismetStringLibrary'"`,
  KismetTextLibrary:   `"/Script/CoreUObject.Class'/Script/Engine.KismetTextLibrary'"`,
  KismetArrayLibrary:  `"/Script/CoreUObject.Class'/Script/Engine.KismetArrayLibrary'"`,
  GameplayStatics:     `"/Script/CoreUObject.Class'/Script/Engine.GameplayStatics'"`,
};
const LIBS_SHORT = {
  KismetMathLibrary:   `Class'"/Script/Engine.KismetMathLibrary"'`,
  KismetSystemLibrary: `Class'"/Script/Engine.KismetSystemLibrary"'`,
  KismetStringLibrary: `Class'"/Script/Engine.KismetStringLibrary"'`,
  KismetTextLibrary:   `Class'"/Script/Engine.KismetTextLibrary"'`,
  KismetArrayLibrary:  `Class'"/Script/Engine.KismetArrayLibrary"'`,
  GameplayStatics:     `Class'"/Script/Engine.GameplayStatics"'`,
};
export const UE_LIBS = UE_VERSION === 'SHORT' ? LIBS_SHORT : LIBS_FULL;

// PinSubCategoryObject / StructType для struct-пинов.
const STRUCTS_FULL = {
  Vector:      `"/Script/CoreUObject.ScriptStruct'/Script/CoreUObject.Vector'"`,      // confirmed (copy-back LineTraceSingle, UE 5.8)
  Rotator:     `"/Script/CoreUObject.ScriptStruct'/Script/CoreUObject.Rotator'"`,
  Vector2D:    `"/Script/CoreUObject.ScriptStruct'/Script/CoreUObject.Vector2D'"`,
  Transform:   `"/Script/CoreUObject.ScriptStruct'/Script/CoreUObject.Transform'"`,
  LinearColor: `"/Script/CoreUObject.ScriptStruct'/Script/CoreUObject.LinearColor'"`, // confirmed (copy-back H1/J5)
  HitResult:   `"/Script/CoreUObject.ScriptStruct'/Script/Engine.HitResult'"`,        // confirmed (copy-back LineTraceSingle)
  Key:         `"/Script/CoreUObject.ScriptStruct'/Script/InputCore.Key'"`,
  LatentActionInfo: `"/Script/CoreUObject.ScriptStruct'/Script/Engine.LatentActionInfo'"`, // confirmed (copy-back Delay L1/L2)
  // InputActionValue — только EnhancedInput: в словаре отсутствует намеренно.
};
// SHORT: правдоподобная legacy-форма (UE4/ранние UE5), вставкой НЕ проверена.
const STRUCTS_SHORT = {
  Vector:           `ScriptStruct'"/Script/CoreUObject.Vector"'`,
  Rotator:          `ScriptStruct'"/Script/CoreUObject.Rotator"'`,
  Vector2D:         `ScriptStruct'"/Script/CoreUObject.Vector2D"'`,
  Transform:        `ScriptStruct'"/Script/CoreUObject.Transform"'`,
  LinearColor:      `ScriptStruct'"/Script/CoreUObject.LinearColor"'`,
  HitResult:        `ScriptStruct'"/Script/Engine.HitResult"'`,
  Key:              `ScriptStruct'"/Script/InputCore.Key"'`,
  LatentActionInfo: `ScriptStruct'"/Script/Engine.LatentActionInfo"'`,
  InputActionValue: `ScriptStruct'"/Script/EnhancedInput.InputActionValue"'`,
};
export const UE_STRUCTS = UE_VERSION === 'SHORT' ? STRUCTS_SHORT : STRUCTS_FULL;

// Enum-пины: PinCategory="byte" + PinSubCategoryObject=путь энама (+ DefaultValue с именем элемента).
const ENUMS_FULL = {
  ETraceTypeQuery: `"/Script/CoreUObject.Enum'/Script/Engine.ETraceTypeQuery'"`, // confirmed (copy-back LineTraceSingle, UE 5.8)
  EDrawDebugTrace: `"/Script/CoreUObject.Enum'/Script/Engine.EDrawDebugTrace'"`, // confirmed (copy-back LineTraceSingle, UE 5.8)
};
const ENUMS_SHORT = {
  ETraceTypeQuery: `Enum'"/Script/Engine.ETraceTypeQuery"'`,
  EDrawDebugTrace: `Enum'"/Script/Engine.EDrawDebugTrace"'`,
};
export const UE_ENUMS = UE_VERSION === 'SHORT' ? ENUMS_SHORT : ENUMS_FULL;

// Все известные значения (оба формата) — для валидатора (пул без ложных W10).
export const ALL_SUBOBJ = [...Object.values(STRUCTS_FULL), ...Object.values(STRUCTS_SHORT), ...Object.values(ENUMS_FULL), ...Object.values(ENUMS_SHORT)];

// Стандартные макросы StandardMacros — для K2Node_MacroInstance.
// guid:null = GUID не захвачен из движка: вставь ноду в UE, скопируй обратно, впиши GraphGuid.
export const UE_MACROS = {
  ForLoop:          { graph: 'ForLoop',          guid: '55C904AF4B45FE1761FB55A8DB9FB801' }, // confirmed (copy-back J7, UE 5.8)
  ForEachLoop:      { graph: 'ForEachLoop',      guid: '99DBFD5540A796041F72A5A9DA655026' }, // confirmed (copy-back, UE 5.8)
  FlipFlop:         { graph: 'FlipFlop',         guid: 'BFFFAAE4434E166F549665AD1AA89B60' }, // medium (дамп UE5)
  ForLoopWithBreak: { graph: 'ForLoopWithBreak', guid: null },
  WhileLoop:        { graph: 'WhileLoop',        guid: null },
  Gate:             { graph: 'Gate',             guid: null },
  DoOnce:           { graph: 'DoOnce',           guid: null },
  DoN:              { graph: 'DoN',              guid: null },
};

// Class-ссылка для object-пинов (WCO): путь класса → ссылка в стиле версии.
// FULL: "/Script/CoreUObject.Class'/Script/CoreUObject.Object'" (copy-back H1, UE 5.8).
export function classRef(classPath){
  return UE_VERSION === 'SHORT' ? `Class'"${classPath}"'` : `"/Script/CoreUObject.Class'${classPath}'"`;
}

export function memberParentRef(lib){
  const p = UE_LIBS[lib];
  if(!p) throw new Error(`Unknown UE lib: ${lib}`);
  return `MemberParent=${p}`;
}

export function structRef(structName){
  const p = UE_STRUCTS[structName];
  if(!p) throw new Error(`Unknown UE struct for ${UE_VERSION}: ${structName}`);
  return p;
}

const MACRO_GRAPH_TPL = g => UE_VERSION === 'SHORT'
  ? `EdGraph'"/Engine/EditorBlueprintResources/StandardMacros.StandardMacros:${g}"'`
  : `"/Script/Engine.EdGraph'/Engine/EditorBlueprintResources/StandardMacros.StandardMacros:${g}'"`;
const MACRO_BP_TPL = UE_VERSION === 'SHORT'
  ? `Blueprint'"/Engine/EditorBlueprintResources/StandardMacros.StandardMacros"'`
  : `"/Script/Engine.Blueprint'/Engine/EditorBlueprintResources/StandardMacros.StandardMacros'"`;

export function macroGraphRef(graph, guid){
  const g = MACRO_GRAPH_TPL(graph);
  const gp = (guid && guid.length >= 32) ? guid : null;
  const guidPart = gp ? `,GraphGuid=${gp.slice(0,8)}${gp.slice(8,12)}${gp.slice(12,16)}${gp.slice(16,20)}${gp.slice(20,32)}` : '';
  return `MacroGraphReference=(MacroGraph=${g},GraphBlueprint=${MACRO_BP_TPL}${guidPart})`;
}
